### POST login
POST http://localhost:8080/api/login
Content-Type: application/json

{
  "email": "user@example.com",
  "password": "passwordpassword"
}

> {%
    client.global.set("auth_token", response.body.token);
%}

### POST register
POST http://localhost:8080/api/register
Content-Type: application/json

{
  "email": "user@example.com",
  "password": "passwordpassword",
  "firstName": "John",
  "lastName": "Doe"
}

> {%
    client.global.set("auth_token", response.body.token);
%}
